### ISSUE TITLE
无法使用脚本

### ISSUE THREAD

**Issue by 453603129** [voltachan/exhentai#1]
你好，我使用了E-Hentai 自动登录脚本，但是无法登陆，已经清除了浏览器的 Cookies 和缓存，我用的是百分浏览器，脚本也已安装成功。

**Comment by voltachan** [comment]
请尝试更新脚本，并检测Cookies的内容是否如下图。
![1.png](https://i.loli.net/2020/02/18/QlAgTVMkYtpZNdn.png)
