### ISSUE TITLE
您好，请问这个为什么可以解决白屏啊

### ISSUE THREAD

**Issue by 0hellocat0** [voltachan/exhentai#2]
这里纯小白orz
最近一段时间用梯子看eh开始白屏进不去（exh不用梯子可以裸连），看别的地方说白屏是ip问题，可是这个脚本可以连接eh，但并不是自己的账号。我想用自己的账号上eh的话该怎样做呢

**Comment by voltachan** [comment]
。。。E站账号也没什么福利啊。。。下载也不能加速啥的。。。
而且我看内容和E-站差不多，E-站是不用登账号的
白屏估计是账号注册时间限制，过十天半个月的应该可以了

**Comment by 0hellocat0** [comment]
> 。。。E站账号也没什么福利啊。。。下载也不能加速啥的。。。
> 而且我看内容和E-站差不多，E-站是不用登账号的
> 白屏估计是账号注册时间限制，过十天半个月的应该可以了

啊我的意思是 我看到有人在eh的论坛上说白屏是因为梯子的ip被eh网主动屏蔽了。但是我用您的脚本就可以用同一个梯子正常登录eh，想知道其中的奥妙，所以向您请教。
用脚本登录的话并不是我的账号，我想用自己的账号登录eh，同时不出现白屏问题。
以及我的账号是之前就申请的了，去年的时候也很正常，最近梯子换服务器之后出现的白屏。
（exh裸连可以登录，但是裸连速度不尽人意并且exh不能进行买gp等操作所以

**Comment by voltachan** [comment]
感觉网上说的坑基本我一踩一个准 :laughing:
1. 账号是在中国内地注册的。（有一阵子对E-站放开了）
2. 用的是QQ邮箱
3. 注册了大概一个月多点时间吧，还有一个同方法注册了一个星期多点时间，然后都能看里站。

感觉这个是靠运气，和IP没有什么关系吧（笑:grinning:），建议还是重新注册一个，主要还是看手气吧:wink:

***不过你可以在本账号买GP，我尽量不跑路。***

**Comment by 0hellocat0** [comment]
> 感觉网上说的坑基本我一踩一个准 😆
> 
> 1. 账号是在中国内地注册的。（有一阵子对E-站放开了）
> 2. 用的是QQ邮箱
> 3. 注册了大概一个月多点时间吧，还有一个同方法注册了一个星期多点时间，然后都能看里站。
> 
> 感觉这个是靠运气，和IP没有什么关系吧（笑😀），建议还是重新注册一个，主要还是看手气吧😉
> 
> _**不过你可以在本账号买GP，我尽量不跑路。**_

账号是13年注册的，不过用的确实是qq邮箱
但是我不认为是账号问题，因为换了梯子新加的服务器之后就可以上eh了，我觉得是之前服务器的ip问题
您的账号是铜星以上的会员吗？好像如果是铜星以上的等级有一些数据是账号绑定而不是ip绑定的，说不定可以绕开eh的ip黑名单

**Comment by voltachan** [comment]
我没有主动向里面充过钱，等级也是最低的。直到最近，不知道最近谁这么好心充了几百块进去，然后就在榜上300+名左右。:smile:
不过以前也没有出现IP限制的现象。

**Comment by 0hellocat0** [comment]
> 我没有主动向里面充过钱，等级也是最低的。直到最近，不知道最近谁这么好心充了几百块进去，然后就在榜上300+名左右。😄
> 不过以前也没有出现IP限制的现象。

我这里也是之前没有问题，直到本月初墙加固了一次然后我用的梯子服务商换了服务器
您说的这个充了几百块是指的向eh官方捐赠吗？捐赠20美金可以变成铜星会员

**Comment by voltachan** [comment]
这个你可以登录[我的E站](https://e-hentai.org/bitcoin.php)看一下。貌似300多块应该是有的。:smile:
不过没充钱之前也没有过类似的IP限制情况，至少我没遇到过，也没有人反馈。

**Comment by 0hellocat0** [comment]
> 这个你可以登录[我的E站](https://e-hentai.org/bitcoin.php)看一下。貌似300多块应该是有的。😄
> 不过没充钱之前也没有过类似的IP限制情况，至少我没遇到过，也没有人反馈。

之后我没有登录您的账号，但是今晚我捐赠了20美金之后，用会白屏的vpn服务器也不会出现白屏现象了（不过也不排除这两天服务器ip刚好被eh解封的可能性，因为捐赠之前我也没有用这些服务器进行尝试
所以我推测您的账号应该也是铜星以上的会员，这种身份应该能很大程度上避免白屏

**Comment by voltachan** [comment]
感谢你的反馈:smile:

**Comment by 0hellocat0** [comment]
您给我提供了思路，也谢谢您
