### ISSUE TITLE
感谢您的项目

### ISSUE THREAD

**Issue by smaplemao** [voltachan/exhentai#4]
熊猫书签挂了，在这里找到了您的项目，很实用。已给星并提交issue表示感谢。
这里还想请教一下，请问您有考虑过开发手机端访问exhentai的项目吗？

**Comment by voltachan** [comment]
感谢您的star。安卓手机的部分浏览器可以安装油猴插件，iPhone也可以用alook浏览器使用脚本。如果写APP有可能性能比不上专业浏览器，功能也会缺，比如评论和去广告。

**Comment by smaplemao** [comment]
好的，我会去了解，感谢您的建议，祝生活愉快。

**Comment by voltachan** [comment]
以后有时间的话会去考虑移植eh的Android版，届时会通知
